### ISSUE TITLE
Cannot open maps with ChimeraX after creating a set of maps

### ISSUE THREAD

**Issue by mmmtnez** [scipion-em/scipion-em#178] opened 2020-12-23 07:29 UTC
Hi all,

when you execute the protocol pwem/protocols/protocol_sets.py you cannot visualize the maps with ChimeraX. After pressing Anbalyze Results a results' window is opened. When you select File -> Open with ChimeraX the ChimeraX GUI tries to open but finally gets closed. I've observed this in the test:

scipion3 tests pwem.tests.protocols.test_protocols_import_volumes.TestImportVolumes

(there is only one case of creation of set of maps)

**Comment by azazellochg** [comment] 2020-12-23 09:44
Duplicate of the https://github.com/scipion-em/scipion-pyworkflow/issues/157

**Closed by azazellochg** 2020-12-23 09:44 UTC
