### ISSUE TITLE
no moude named pwem.meta

### ISSUE THREAD

**Issue by blank222** [scipion-em/scipion-em#283] opened 2022-01-13 06:51 UTC
When I use GAN in deep denoising to denoise particles, I report ModuleNotFoundError: No module named 'pwem.metadata'

**Comment by pconesa** [comment] 2022-01-13 07:14
Sorry! what is GAN? Is it an option n a denoising protocol? Which protocol is this? and from which plugin?

**Comment by blank222** [comment] 2022-01-13 07:33
Yes, it is an option of denoising protocol, in Deep Denoising of Xmipp3, we need to use the installed deepLearningToolkit plugin.

**Comment by pconesa** [comment] 2022-01-13 08:13
I see, I've assigned this to an xmipp maintainer.

**Comment by blank222** [comment] 2022-01-13 08:16
Thanks a lot.

**Comment by DStrelak** [comment] 2022-01-17 13:49
Hi @blank222 , 
We could not reproduce the error, but we fixed one import which looked suspiciously like what you reported.
The change is present in the devel branch of the Xmipp.
Feel free to test them if you use development version of Xmipp.
Otherwise, the change will be available in the next release sometime this month.

**Closed by DStrelak** 2022-01-17 13:49 UTC
