### ISSUE TITLE
WARNING: Can't get Scipion's plugin list, the plugin repository is not available

### ISSUE THREAD

**Issue by xingxingjiukunkun** [scipion-em/scipion-em#519] opened 2024-07-25 02:40 UTC
When I open the plugin list, it displays

<img width="439" alt="屏幕截图 2024-07-25 103847" src="https://github.com/user-attachments/assets/125646ff-402f-4ffe-835e-725db608e450">

**Comment by azazellochg** [comment] 2024-07-25 10:42
the server was down, please try again

**Comment by azazellochg** [comment] 2024-07-25 10:43
duplicate of https://github.com/scipion-em/scipion-installer/issues/38

**Closed by azazellochg** 2024-07-25 10:43 UTC
